# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: cmd/confupdatedt.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto

from .. import configdt


@dataclass
class Confupdateopt(betterproto.Message):
    perform: bool = betterproto.bool_field(1)
    new_conf: configdt.Devconf = betterproto.message_field(2)
