# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: configdt.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto

from .sensors import cpudt
from .sensors import raspcamdt


@dataclass
class Time(betterproto.Message):
    hour: int = betterproto.int32_field(1)
    minute: int = betterproto.int32_field(2)


@dataclass
class Modconf(betterproto.Message):
    rasp_cam: raspcamdt.Raspcamopt = betterproto.message_field(1)
    cpu: cpudt.Cpuopt = betterproto.message_field(2)


@dataclass
class Devconf(betterproto.Message):
    mqtt_host: str = betterproto.string_field(1)
    mqtt_port: int = betterproto.int32_field(2)
    mqtt_user: str = betterproto.string_field(3)
    mqtt_pass: str = betterproto.string_field(4)
    burst_interval: int = betterproto.int32_field(5)
    burst_count: int = betterproto.int32_field(6)
    wake_on: List["Time"] = betterproto.message_field(7)
    sensor_conf: "Modconf" = betterproto.message_field(8)
