# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: packetdt.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto

from . import cmddt
from . import sensordt


@dataclass
class Packet(betterproto.Message):
    uid: str = betterproto.string_field(1)
    cmds: cmddt.Cmdin = betterproto.message_field(3, group="type")
    out: sensordt.Sensorout = betterproto.message_field(4, group="type")
