# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: sensordt.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto

from .sensors import cpudt
from .sensors import genericdt
from .sensors import raspcamdt
from .sensors import systemdt


@dataclass
class Output(betterproto.Message):
    cpu: cpudt.Cpuout = betterproto.message_field(1, group="output")
    cam: raspcamdt.Raspcamout = betterproto.message_field(2, group="output")
    system: systemdt.Systemout = betterproto.message_field(3, group="output")
    generic: genericdt.Genericout = betterproto.message_field(4, group="output")


@dataclass
class Sensorout(betterproto.Message):
    outputs: List["Output"] = betterproto.message_field(2)
