# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: sensors/cpudt.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class Cpuopt(betterproto.Message):
    pass


@dataclass
class Cpuout(betterproto.Message):
    load: float = betterproto.float_field(1)
    count: int = betterproto.int32_field(2)
    pkg_temp: float = betterproto.float_field(3)
