# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: sensors/genericdt.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class Genericopt(betterproto.Message):
    pass


@dataclass
class Genericout(betterproto.Message):
    value: float = betterproto.float_field(1)
    name: str = betterproto.string_field(2)
