# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: sensors/raspcamdt.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


class Encoding(betterproto.Enum):
    JPEG = 0
    PNG = 1
    BMP = 2
    GIF = 3


class Exposure(betterproto.Enum):
    EXP_OFF = 0
    EXP_AUTO = 1
    EXP_NIGHT = 2
    EXP_NIGHTPREVIEW = 3
    EXP_BACKLIGHT = 4
    EXP_SPOTLIGHT = 5
    EXP_SPORTS = 6
    EXP_SNOW = 7
    EXP_BEACH = 8
    EXP_VERYLONG = 9
    EXP_FIXEDFPS = 10
    EXP_ANTISHAKE = 11
    EXP_FIREWORKS = 12


class Awb(betterproto.Enum):
    AWB_OFF = 0
    AWB_AUTO = 1
    AWB_SUN = 2
    AWB_CLOUD = 3
    AWB_SHADE = 4
    AWB_TUNGSTEN = 5
    AWB_FLUORESCENT = 6
    AWB_INCANDESCENT = 7
    AWB_FLASH = 8
    AWB_HORIZON = 9
    AWB_GREYWORLD = 10


class Imxfx(betterproto.Enum):
    IMXFX_NONE = 0
    IMXFX_NEGATIVE = 1
    IMXFX_SOLARISE = 2
    IMXFX_SKETCH = 3
    IMXFX_DENOISE = 4
    IMXFX_EMBOSS = 5
    IMXFX_OILPAINT = 6
    IMXFX_HATCH = 7
    IMXFX_GPEN = 8
    IMXFX_PASTEL = 9
    IMXFX_WATERCOLOUR = 10
    IMXFX_FILM = 11
    IMXFX_BLUR = 12
    IMXFX_SATURATION = 13
    IMXFX_COLOURSWAP = 14
    IMXFX_WASHEDOUT = 15
    IMXFX_POSTERISE = 16
    IMXFX_COLOURPOINT = 17
    IMXFX_COLOURBALANCE = 18
    IMXFX_CARTOON = 19


@dataclass
class Raspcamout(betterproto.Message):
    encoding: "Encoding" = betterproto.enum_field(1)
    bin: bytes = betterproto.bytes_field(2)


@dataclass
class Raspcamopt(betterproto.Message):
    vflip: bool = betterproto.bool_field(1)
    hflip: bool = betterproto.bool_field(2)
    rotation: int = betterproto.int32_field(3)
    quality: int = betterproto.int32_field(4)
    encoding: "Encoding" = betterproto.enum_field(5)
    sharpness: int = betterproto.int32_field(6)
    contrast: int = betterproto.int32_field(7)
    brightness: int = betterproto.int32_field(8)
    saturation: int = betterproto.int32_field(9)
    exposure: "Exposure" = betterproto.enum_field(10)
    awb: "Awb" = betterproto.enum_field(11)
    imxfx: "Imxfx" = betterproto.enum_field(12)
