# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: sensors/systemdt.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class Systemopt(betterproto.Message):
    pass


@dataclass
class Systemout(betterproto.Message):
    voltage: float = betterproto.float_field(1)
    wifi_signal: float = betterproto.float_field(2)
